miketheman/pytest-socket

.travis.yml
appveyor.yml
pytest_socket.py
setup.py
tests/test_socket.py
tox.ini

I like this plugin a lot but the by-default blocking really hinders its usefulness. If you install it in a global environment then all py.test runs will be unintentionally affected. I suggest removing that default behavior, which this PR does.
I also introduced the following changes.
* Add `@pytest.mark.disable_socket` and `@pytest.mark.enable_socket` to conveniently mark tests without importing the package.
* Add `socket_disabled` and `socket_enabled` fixtures.
* Add `--disable-socket` CLI option. This can be also used to easily disable the socket by default by adding it to `pytest.ini`.
* Create a separate `SocketBlockedError` exception that is easier to check against in tests, if necessary.
* Simplify the socket blocking code.
* Remove any printed messages. This is just unnecessary …

Reorganize the API

---

tests/test_socket.py

As of pytest 3.2.0, the internal outcome class no longer inherits from Exception, rather from BaseException.
This was reported in pytest-dev/pytest#580 and changed in pytest-dev/pytest#2490

Change the inherited exception class in tests

---

.codeclimate.yml
.travis.yml

Follows:
- https://docs.codeclimate.com/docs/configuring-test-coverage
- https://docs.codeclimate.com/docs/travis-ci-test-coverage

Add codeclimate to travis output

---

.gitignore
README.rst
pytest_socket.py
tests/test_restrict_hosts.py
tox.ini

This is an alternative approach to https://github.com/miketheman/pytest-socket/pull/8 for #6. 
It is much cleaner, but i couldn't (and i did try) to get the tests passing in `pypy` and `python2.7`, but I failed, so i had to change the `tox.ini` envlist to `envlist = py34,py35,py36,flake8,coverage` for a passing mark (kinda hoping it passes during CI...). I think it's to do with the `pytest-localserver` module, but I can't see why and there don't appear to be any issues reported. I also tried starting my own vanilla python http server in `test_restrict_hosts.py` before the tests started, but that caused other errors with pypy... any help appreciated (i think the code itself works fine in all versions).
Since it's very separate functionality, it might be better if we extract it into a …

create second argument for restricting connections to specific hosts

---

tests/test_restrict_hosts.py

Hopefully fixes sporadic test failure in p27 introduced by https://github.com/miketheman/pytest-socket/pull/9

add contextlib to ensure proper closing of connections

---

pytest_socket.py

`node.get_marker` was removed in pytest 4.1. The pytest changelog suggests
using `node.get_closest_marker` as a replacement.
Fixes #16

Replace node.get_marker with node.get_closest_marker

---

tests/test_socket.py

For some reason, the test in pytest 5.x has stopped working with the
existing test case - which has extra text beyond this string, so apply a
wildcard (as probably should have been done originally).

test: extend match to account for wildcard text

---

appveyor.yml

The problem is tox uses an old `virtualenv` from site-packages, see the [log](https://ci.appveyor.com/project/miketheman/pytest-socket/builds/27806599/job/rc5qa94e9b7nlcgg#L48) in the last build:
```
48 Requirement already satisfied: virtualenv>=14.0.0 in c:\python27\lib\site-packages (from tox) (15.0.1)
```
and this virtualenv has installed `pip==8.1.1` inside, see the [warning](https://ci.appveyor.com/project/miketheman/pytest-socket/builds/27806599/job/rc5qa94e9b7nlcgg#L110):
```
110 You are using pip version 8.1.1, however version 19.2.3 is available.
111 You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
which can't handle the enviroment markers ([PEP 496](https://www.python.org/dev/peps/pep-0496/)) properly. The support of environment markers …

Upgrade to the latest virtualenv in AppVeyor

---

pytest_socket.py
tests/test_socket.py

As reported in a couple of issues, the usage of markers (not fixtures)
was misbehaving, as the order in which the `_socket_marker` evaluation
was occurring left the command-line option disabled.
Fixes #15
Closes #28
Co-authored-by: Calvin Behling <calvin.behling@gmail.com>
Signed-off-by: Albert Tugushev <albert@tugushev.ru>
Signed-off-by: Matt Callaghan <mcallaghan-bsm@users.noreply.github.com>

fix: correctly set fixture when using markers

---

.github/workflows/python.yml
pyproject.toml

Support for Python 3.5 ended 13 September 2020.
Tools like `poetry` and `pip` will be removing their support soon, so
before their removal hits us, remove the support from the plugin.
Resolved #51

chore: remove support for python 3.5

---

pytest_socket.py
tests/test_socket.py

Thanks for providing this really useful extension to `pytest`.
Recently, using `pytest-socket` interfered with the `docker` package, which started subclassing `socket.socket`; and obviously failed since this package changes it to be a function rather than a class.
In this patch, I've replaced the socket guard with a class deriving from `socket.socket`, but overriding the `__new__` method such that any attempt to instantiate it results in the same error as before.

Avoid changing the type of `socket.socket` to function.

---

pytest_socket.py
tests/test_socket.py

This is a pretty dumb implementation and I'm happy to rework it to be a bit safer/defensive, just wanted to test if it worked first. It fixes issues with `asyncio` by check if it's an `AF_UNIX` domain socket being requested and allowing that, otherwise it blocks as normal.
should help with
https://github.com/miketheman/pytest-socket/issues/47
https://github.com/miketheman/pytest-socket/issues/6
I've tested it with both the starlette example and the `asynctest` example and both work with this patch
```
import asynctest
class TestClass(asynctest.TestCase):
async def test_something(self):
pass
```

Don't block unix sockets

---

README.rst

docs: add details on fixture scope

---

pyproject.toml
tests/test_async.py

While the basics of asyncio ought to be covered by enabling unix
sockets in #54, I thought it might be nice to add some explicit asyncio
tests to ensure that we don't hit any framework-specific regressions.
I had written these locally when testing the changes anyhow.
Refs: #6
Refs: #47

test: add testing for some async frameworks

---

pyproject.toml

pyproject.toml: include tests in sdist archive

---

README.md

If you follow the instructions in the README for adding pytest-socket to your setup.cfg, you get:
```
Failed: [pytest] section in setup.cfg files is no longer supported, changeto [tool:pytest] instead.
```
This PR adds the correct syntax for setup.cfg, and also links to the pytest documentation for the different configuration locations.

docs: Fix syntax for setup.cfg

---

.gitignore
Makefile

The existing behavior relied on making the package "installable" and
having a resulting `.egg-info` file to inform Make on whether to run the
installation again.
Poetry removed that behavior, so now we set our own stamp file when
completing the installation.

chore(dev): update development commands

---

pyproject.toml
pytest_socket.py
tests/test_async.py

Fix pytest-socket raises IndexError with httpx

---

tests/conftest.py
tests/test_socket.py

As we build out more test cases, we want to reenable the default
behavior after each test.

test: move the reenable fixture to conftest

---

pytest_socket.py
tests/test_socket.py

Handle `family` passed as keyword argument to `socket` constructor

Handle `family` passed as keyword argument

---

.codeclimate.yml

Now we allow B ratings.
See https://docs.codeclimate.com/docs/radon for more.

chore: allow for a little complexity

---

pytest_socket.py

These actions can conflict with other tests within scope,
and should already be covered by `pytest_runtest_teardown()`.
Make teardown a private function, since it's not meant to be used outside this plugin.
Add resetting the socket back to normal as well.

chore: remove post-yield behaviors

---

pytest_socket.py
tests/test_precedence.py

When the plugin started out, I didn't know how to use the
`runtest_setup` phase, so I used an automatically-used fixture.
I've now removed the fixture, which may have had unintended side effects with other plugins or test suites.
I've also changed the ordering, to be more inline with the expected behaviors, as I laid out in https://github.com/miketheman/pytest-socket/discussions/81#discussion-3670981 
I've added a bunch of tests that express the desired precedence behavior in a test module `tests/test_precedence.py` and all the existing tests pass as well 🎉 .
This, and a few other bits, should lead to an 0.50.0 release.

refactor/fix: move logic into setup phase and correct order

---

tests/test_combinations.py

First test: Confirms combo of fixture and allow-host CLI flags work.
Resolves #56

test: add test module for combinations

---

pytest_socket.py
tests/test_combinations.py

When combining configuration parameters, a UNIX socket was being
guarded, despite being allowed via config, since the allow-hosts config
was passed.
Resolves #78

fix: test allow_hosts for unix sockets

---

tests/test_async.py
tests/test_restrict_hosts.py
tests/test_socket.py

This was added for some ancient reason, and is no longer needed.

chore: remove verbose flag from tests

---

tests/conftest.py
tests/test_async.py
tests/test_combinations.py
tests/test_socket.py

Instead of implementing and importing the same feature across modules,
put it somewhere common.
The removals are for a behavior that is no longer needed now that the
teardown phase cleans up after itself.

test: move unix decorator to conftest

---

.github/workflows/python.yml
pyproject.toml

Python 3.6 is End Of Life on 23 Dec 2021
Python 3.10 was released 04 Oct 2021

chore: update python versions

---

.github/workflows/python.yml
Makefile
pyproject.toml
pytest.ini

Using pytest-cov wasn't conducive to testing pytest **plugins**.
Replace the plugin with command line invocation.
The `pyproject.toml` syntax needed to be updated to have all entries in
the `include` list to be the same type of object, thanks to to the
`toml` library.
Resolves #58

test: replace coverage command

---

pytest_socket.py
tests/test_restrict_hosts.py

We no longer support Python 2.7, or anything below Python 3.6.
We can now safely use f-strings and terser syntax.
**refactor**: remove unnecessary parsing 
The `httpbin` fixture gives us both `host` and `port` attributes, so we
can use them directly instead of parsing a constructed URL from the same
parts.

refactor: replace .format with f-strings

---

.flake8
.pre-commit-config.yaml
README.md
pyproject.toml
pytest_socket.py
tests/conftest.py
tests/test_async.py
tests/test_combinations.py
tests/test_restrict_hosts.py
tests/test_socket.py

Apply opinionated style to codebase.
Whole lotta lint, no changes.

lint: apply black

---

pytest_socket.py
tests/test_doctest.py

Fix AttributeError: 'DoctestItem' object has no attribute 'fixturenames'.
Fix #105.
I am piggybacking on @orf's pull request and adding a test to it: #107
Thank you both!

fix: don't break on doctests

---

Makefile

The `make install` target has evolved a bit, and now if a new project
checks out the code and runs `make`, we should expect that the
dependencies get installed and the tests run.
Of course, this is predicated on the existence of `poetry`, which is
already handled.
Fixes #60

chore: update make target to handle installation

---

.pre-commit-config.yaml
pyproject.toml

With a werkzeug update, tests being to fail, as httpbin has not updated
their dependencies and import paths to match.
Include a specific revision of a fix.
Consider a future change replacing `httpbin` with something that has
more support, as `httpbin` appears to be unmaintained.

fix(deps): pin httpbin to a fixed version

---

.pre-commit-config.yaml
pyproject.toml
pytest_socket.py

Part of the pre-commit stack, so we prevent it from sneaking in.
Signe-off-by: Mike Fiedler <miketheman@gmail.com>

test: add vulture to detect dead code

---

.github/workflows/codesee-arch-diagram.yml

Was introduced with CodeSee, broke pre-commit checks after that.

chore: remove trailing whitespace

---

.github/workflows/python.yml
Makefile

Prior refactoring to use `poetry` for dependency management, the `coverage` command was executed directly. This was changed to use `poetry run` to ensure the correct version of `coverage` was used.
However, the `coverage report` command was not updated to use `poetry run` and thus was not using the correct version of `coverage`.

test: correct execution runner for coverage report

---

pytest_socket.py
tests/test_restrict_hosts.py

This is equivalent to #80 but brought up to date with `main`. This is necessary when using `docker-compose` to avoid having to assign static IPs to specific services.

feat(allow_hosts): add support for hostname resolution

---

tests/test_socket.py

httpbin has proven pretty flaky, so use something more reliable.
Origin: https://github.com/aaronpowell/httpstatus
Resolves #229

test: update test remote with stable service

---

pyproject.toml

As the file contents are already being included in the wheel's `dist-info` folder either alone or embedded into PKG-INFO, we don't need to emit these ourselves.
Resolves #230

fix: only emit license and readme for sdist

---

.github/workflows/python.yml

If the test suite fails, the coverage report would still run.

test: don't fail silently

---

poetry.lock
pyproject.toml

Now that there's an updated, maintained version, remove the pinning to a hash, and let dependency resolution do its thing.
Removes some heavier dev deps like gevent, brotlipy, and more.
EDIT: Had to pin to a newer revision on a different repo, due to unreleased werkzeug fixen: https://github.com/psf/httpbin/issues/35

chore(dependencies): update custom httpbin pin

---

README.md
poetry.lock
pyproject.toml
pytest_socket.py
tests/test_restrict_hosts.py

To avoid resolving the allowed hostnames once per test, cache the results in a shared dict. This should result in one set of resolutions per pytest run (or test worker, under pytest-xdist). I did this in a backward-compatible manner by introducing an optional parameter to the `socket_allow_hosts()` and `normalize_allowed_hosts()` functions as they appear to be public API, albeit undocumented.
I also refactored the plugin [to use Stash](https://docs.pytest.org/en/7.0.x/how-to/writing_hook_functions.html#plugin-stash), which was introduced in pytest 7.0.0, rather than set attributes on Config. If you want to keep support for `pytest>=6.2.5` I can back that bit out, I just thought it improved clarity.

Cache name resolutions

---

tests/test_combinations.py

When not using the `www` prefix SSL negotiation can take 60+ seconds locally, which is annoying and slow.

test: update real endpoint in test
